[package]
edition = "2021"
name = "rust-linux-safe-demo"
version = "0.1.0"

[dependencies]
linux-io = {path = "../linux-io", default-features = false}
linux-unsafe = {path = "../linux-unsafe"}

[package.metadata.release]
release = false
