[package]
edition = "2021"
name = "rust-linux-safe-demo"
version = "0.1.0"

[dependencies]
linux-io = {path = "../linux-io", default-features = false}
linux-unsafe = {version = "0.3.0"}

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[package.metadata.release]
release = false
